version: '3'

services:
  mysql:
    image: mysql:8.0.30-debian
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce_db
      MYSQL_PASSWORD: root
    ports:
      - 3308:3306
    volumes:
      - .docker/mysql:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql